diff --git a/Makefile b/Makefile
index 431933ca..59d284ac 100644
--- a/Makefile
+++ b/Makefile
@@ -1,10 +1,10 @@
 GPU=0
 CUDNN=0
 CUDNN_HALF=0
-OPENCV=0
+OPENCV=1
 AVX=0
 OPENMP=0
-LIBSO=0
+LIBSO=1
 ZED_CAMERA=0
 ZED_CAMERA_v2_8=0
 
@@ -67,22 +67,26 @@ LIBNAMESO=libdarknet.so
 APPNAMESO=uselib
 endif
 
-ifeq ($(USE_CPP), 1)
-CC=g++
-else
-CC=gcc
-endif
-
-CPP=g++ -std=c++11
-NVCC=nvcc
+#CPP=g++ -std=c++11
+#NVCC=nvcc
 OPTS=-Ofast
 LDFLAGS= -lm -pthread
 COMMON= -Iinclude/ -I3rdparty/stb/include
-CFLAGS=-Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pragmas -fPIC
+CFLAGS=-fPIC -Wall -Wfatal-errors \
+	-Wno-unused-result \
+	-Wno-unknown-pragmas \
+	-Wno-maybe-uninitialized \
+	-Wno-implicit-function-declaration \
+	-Wno-sign-compare \
+	-Wno-unused-variable \
+	-Wno-unused-value \
+	-Wno-unused-but-set-variable \
+	-Wno-parentheses \
+	-Wno-stringop-overflow \
+	-Wno-switch \
+	-Wno-unused-function
 
 ifeq ($(DEBUG), 1)
-#OPTS= -O0 -g
-#OPTS= -Og -g
 COMMON+= -DDEBUG
 CFLAGS+= -DDEBUG
 else
